<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Ejercicio-11" data-toc-modified-id="Ejercicio-11-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Ejercicio 11</a></span><ul class="toc-item"><li><span><a href="#Árboles-de-desición" data-toc-modified-id="Árboles-de-desición-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Árboles de desición</a></span></li><li><span><a href="#Estado-del-arte" data-toc-modified-id="Estado-del-arte-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Estado del arte</a></span><ul class="toc-item"><li><span><a href="#Clasificación" data-toc-modified-id="Clasificación-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Clasificación</a></span></li></ul></li><li><span><a href="#Implementación" data-toc-modified-id="Implementación-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Implementación</a></span></li><li><span><a href="#Referencias" data-toc-modified-id="Referencias-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Referencias</a></span></li></ul></li></ul></div>

## Ejercicio 11

### Árboles de desición

### Estado del arte

Los árboles de decisión (DT) son un método de aprendizaje supervisado no paramétrico utilizado para la clasificación y la regresión. El objetivo es crear un modelo que prediga el valor de una variable objetivo aprendiendo reglas de decisión simples inferidas de las características de los datos. Un árbol puede verse como una aproximación constante a trozos.

Por ejemplo, en el siguiente ejemplo, los árboles de decisión aprenden de los datos para aproximarse a una curva sinusoidal con un conjunto de reglas de decisión if-then-else. Cuanto más profundo sea el árbol, más complejas son las reglas de decisión y más ajustado es el modelo.

![Árbol de decisión](./Multimedia/ad.png)

Algunas ventajas de los árboles de decisión son:

- Fácil de entender e interpretar. Los árboles se pueden visualizar.
- Requiere poca preparación de datos. Otras técnicas a menudo requieren la normalización de los datos, es necesario crear variables ficticias y eliminar los valores en blanco. Algunas combinaciones de árboles y algoritmos admiten valores que faltan.
- El costo de usar el árbol (es decir, predecir datos) es logarítmico en el número de puntos de datos utilizados para entrenar el árbol.
- Capaz de manejar datos numéricos y categóricos. Sin embargo, la implementación de scikit-learn no admite variables categóricas por ahora. Otras técnicas suelen estar especializadas en el análisis de conjuntos de datos que tienen un solo tipo de variable. Consulte los algoritmos para obtener más información.
- Capaz de manejar problemas de salida múltiple.
- Utiliza un modelo de caja blanca. Si una situación dada es observable en un modelo, la explicación de la condición se explica fácilmente con la lógica booleana. Por el contrario, en un modelo de caja negra (por ejemplo, en una red neuronal artificial), los resultados pueden ser más difíciles de interpretar.
- Es posible validar un modelo utilizando pruebas estadísticas. Eso hace posible tener en cuenta la fiabilidad del modelo.
- Funciona bien incluso si sus suposiciones son algo violadas por el verdadero modelo a partir del cual se generaron los datos.

Las desventajas de los árboles de decisión incluyen:

- Los estudiantes del árbol de decisiones pueden crear árboles demasiado complejos que no generalizan bien los datos. Esto se llama sobreajuste. Para evitar este problema son necesarios mecanismos como la poda, el establecimiento del número mínimo de muestras requeridas en un nodo de la hoja o el establecimiento de la profundidad máxima del árbol.
- Los árboles de decisión pueden ser inestables porque pequeñas variaciones en los datos pueden dar lugar a la generación de un árbol completamente diferente. Este problema se mitiga mediante el uso de árboles de decisión dentro de un conjunto.
- Las predicciones de los árboles de decisión no son ni suaves ni continuas, sino aproximaciones constantes a trozos como se ve en la figura anterior. Por lo tanto, no son buenos en la extrapolación.
- Se sabe que el problema de aprender un árbol de decisiones óptimo es NP-completo bajo varios aspectos de la optimización e incluso para conceptos simples. En consecuencia, los algoritmos prácticos de aprendizaje del árbol de decisiones se basan en algoritmos heurísticos como el algoritmo codicioso, donde se toman decisiones localmente óptimas en cada nodo. Tales algoritmos no pueden garantizar el retorno del árbol de decisiones óptimo a nivel mundial. Esto se puede mitigar entrenando múltiples árboles en un alumno de conjunto, donde las características y las muestras se muestrean al azar con reemplazo.
- Hay conceptos que son difíciles de aprender porque los árboles de decisión no los expresan fácilmente, como XOR, paridad o problemas de multiplexores.
- Los estudiantes del árbol de decisiones crean árboles sesgados si dominan algunas clases. Por lo tanto, se recomienda equilibrar el conjunto de datos antes de encajar con el árbol de decisiones.

#### Clasificación

Al igual que con otros clasificadores,DecisionTreeClassifier toma como entrada two arrays: an array X, sparse or dense, of shape (n_samples, n_features) holding the training samples, and an array Y of integer values, shape (n_samples,), holding the class labels for the training sample.

![Árbol de decisión ejemplo](./Multimedia/ejad.png)

### Implementación

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
iris = load_iris()
X, y = iris.data, iris.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [4]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [5]:
y_pred = clf.predict(X_test)

In [6]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [7]:
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 100.00%


In [8]:
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [9]:
def predecir_tipo_pétalo(modelo, nueva_observación):
    # La nueva_observación debe ser un arreglo de 1D con las características de la flor
    # Devolver el tipo de pétalo predicho
    return iris.target_names[clf.predict([nueva_observación])][0]

In [10]:
nueva_observacion = np.array([5.1, 3.5, 1.4, 0.2])  # Cambia estos valores según la nueva observación
tipo_petalo_predicho_tree = predecir_tipo_pétalo(clf, nueva_observacion)
print('Tipo de pétalo predicho por el Árbol de Decisiones:', tipo_petalo_predicho_tree)

Tipo de pétalo predicho por el Árbol de Decisiones: setosa


### Referencias

[1] J. Grus, Data Science From Scratch: First Principles With Python. O'Reilly Media, Inc., 2019.

[2] Desarrolladores de scikit-learn. “1.1. linear models”. scikit-learn. Accedido el 4 de octubre de 2023. [En línea]. Disponible: https://scikit-learn.org/stable/modules/linear_model.html